apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  labels:
    app: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: kttkpmmicroservices-customer-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer-service
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31000
  type: LoadBalancer
# Contract Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contract-service
  labels:
    app: contract-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contract-service
  template:
    metadata:
      labels:
        app: contract-service
    spec:
      containers:
        - name: contract-service
          image: kttkpmmicroservices-contract-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: contract-service
spec:
  selector:
    app: contract-service
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 31001
  type: LoadBalancer

# Payment Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: kttkpmmicroservices-payment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 31002
  type: LoadBalancer
# Statistic Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistic-service
  labels:
    app: statistic-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistic-service
  template:
    metadata:
      labels:
        app: statistic-service
    spec:
      containers:
        - name: statistic-service
          image: kttkpmmicroservices-statistic-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: statistic-service
spec:
  selector:
    app: statistic-service
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 31003
  type: LoadBalancer
